# Built from this template : https://github.com/actions/setup-python
name: Python-Full-CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ['3.10']
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 flake8-match pre-commit pytest
          pip install -r ./dependencies/requirements.txt
      - name: Lint with precommit
        uses: pre-commit/action@v3.0.0
      - name: Run pytest and compile coverage report
        run: |
          python -m pytest --cov=src unittests/ --cov-report term --cov-report html:./docs/source/_static/code_cov/
      - name: Sphinx build
        run: |
          xcopy /s /Y .\.github\workflows\. .\docs\source\_static\github_actions
          sphinx-build -b html ./docs/source ./docs/build
          sphinx-build -b doctest ./docs/source ./docs/build
      - name: Deploy documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/
          force_orphan: true