# Built from this template : https://github.com/actions/setup-python
name: Python-Simple-CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ['3.10']
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 flake8-match pre-commit pytest
        pip install -r ./dependencies/requirements.txt
    - name: Run a simple python command
      run: |
        python -m src.main